name: Deploy WordPress Theme to MilesWeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Theme via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 103.191.209.67
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: admin.brightwebforge.com/wp-content/themes/cicd/ 